# Generated by Django 4.2.3 on 2023-07-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PmanagementGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectcompleted", models.IntegerField(null=True)),
                ("underprogress", models.IntegerField(null=True)),
                ("pending", models.IntegerField(null=True)),
                ("ongoing", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectComplition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("name", models.CharField(max_length=80, null=True)),
                ("iteration", models.CharField(max_length=80, null=True)),
                ("startdate", models.DateTimeField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectcomplitionGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priorities", models.CharField(max_length=80, null=True)),
                ("totalnumberofprojectcomparision", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="projectInduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectname", models.CharField(max_length=80, null=True)),
                ("projectowner", models.CharField(max_length=80, null=True)),
                ("projectnumber", models.IntegerField(null=True)),
                ("date_projectnumber", models.DateTimeField(max_length=80, null=True)),
                ("typeofproject", models.CharField(max_length=80, null=True)),
                ("applicationversion", models.CharField(max_length=80, null=True)),
                (
                    "file_avabilityvarepotfromvender",
                    models.FileField(default=None, upload_to="induction/"),
                ),
                (
                    "file_avabilitysafetohostcertificate",
                    models.FileField(default=None, upload_to="induction1"),
                ),
                (
                    "file_avabilitydesignorarchitecturedocumention",
                    models.FileField(default=None, upload_to="induction2"),
                ),
                (
                    "radio_linkedtopreviousproject",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "NO")],
                        default="None",
                        max_length=10,
                    ),
                ),
                (
                    "radio_avabilityvarepotfromvender",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "NO")],
                        default="None",
                        max_length=10,
                    ),
                ),
                (
                    "radio_avabilitydesignorarchitecturedocumention",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "NO")],
                        default="None",
                        max_length=10,
                    ),
                ),
                (
                    "radio_stagingenvironmentavability",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "NO")],
                        default="None",
                        max_length=10,
                    ),
                ),
                (
                    "radio_ipwhitelisting",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "NO")],
                        default="None",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="projectProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("name", models.CharField(max_length=80, null=True)),
                ("iteration", models.CharField(max_length=80, null=True)),
                ("startdate", models.DateTimeField(max_length=80, null=True)),
                ("projectautomatedvatest", models.CharField(max_length=80, null=True)),
                ("projectmanualtest", models.CharField(max_length=80, null=True)),
                ("projectperformancetest", models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Projectreport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pronumber", models.IntegerField(null=True)),
                ("proname", models.CharField(max_length=80, null=True)),
                ("proiteration", models.CharField(max_length=80, null=True)),
                ("startdate", models.DateTimeField(max_length=80, null=True)),
                ("enddate", models.DateField(max_length=80, null=True)),
                ("provadetils", models.CharField(max_length=80, null=True)),
                ("proseverit", models.CharField(max_length=80, null=True)),
                ("provaparameters", models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="projectStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(null=True)),
                ("projectname", models.CharField(max_length=80, null=True)),
                ("projectiteration", models.CharField(max_length=80, null=True)),
                ("estimatetimeline", models.DateTimeField(max_length=80, null=True)),
                ("lead", models.CharField(max_length=80, null=True)),
                ("automatedvatest", models.CharField(max_length=80, null=True)),
                ("manualtest", models.CharField(max_length=80, null=True)),
                ("performancetest", models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PstatusGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totalnumberofprojectcomplete", models.IntegerField(null=True)),
                ("year", models.IntegerField(null=True)),
            ],
        ),
    ]
