# Generated by Django 4.2.2 on 2023-07-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auditinitiation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectnumber", models.IntegerField(null=True)),
                ("unit", models.CharField(max_length=80, null=True)),
                ("station", models.CharField(max_length=80, null=True)),
                ("detailsofitassests", models.CharField(max_length=80, null=True)),
                ("teamdetails", models.CharField(max_length=80, null=True)),
                ("inititationdate", models.DateTimeField(max_length=80, null=True)),
            ],
        ),
    ]
