# Generated by Django 4.2.2 on 2023-07-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_preauditgraph"),
    ]

    operations = [
        migrations.CreateModel(
            name="quaterlyGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(null=True)),
                ("quaterlyfollowupreportnotreceived", models.IntegerField(null=True)),
            ],
        ),
    ]
