# Generated by Django 4.2.2 on 2023-07-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_quaterlygraph"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditinitiation",
            name="station",
            field=models.TextField(max_length=80, null=True),
        ),
    ]
