# Generated by Django 4.2.2 on 2023-07-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_auditscheduling"),
    ]

    operations = [
        migrations.CreateModel(
            name="auditcomplition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectnumber", models.IntegerField(null=True)),
                ("unit", models.CharField(max_length=80, null=True)),
                ("station", models.CharField(max_length=80, null=True)),
                ("initiationdate", models.DateField(max_length=80, null=True)),
                ("complitiondate", models.DateField(max_length=80, null=True)),
                (
                    "file_selectexcelfile",
                    models.FileField(default=None, upload_to="auditcomplition/"),
                ),
                (
                    "file_finalauditreport",
                    models.FileField(default=None, upload_to="auditcomplition1/"),
                ),
            ],
        ),
    ]
