# Generated by Django 4.2.2 on 2023-07-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_auditcomplition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditcomplition",
            name="file_finalauditreport",
            field=models.FileField(default=None, upload_to="auditcomplition1"),
        ),
        migrations.AlterField(
            model_name="auditcomplition",
            name="file_selectexcelfile",
            field=models.FileField(default=None, upload_to="auditcomplition"),
        ),
    ]
