# Generated by Django 4.2.2 on 2023-07-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_auditcomplition_file_finalauditreport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditcomplition",
            name="file_finalauditreport",
            field=models.FileField(default=None, upload_to="complition1/"),
        ),
        migrations.AlterField(
            model_name="auditcomplition",
            name="file_selectexcelfile",
            field=models.FileField(default=None, upload_to="complition/"),
        ),
        migrations.AlterField(
            model_name="auditscheduling",
            name="file_upload",
            field=models.FileField(default=None, upload_to="scheduling/"),
        ),
        migrations.AlterField(
            model_name="projectinduction",
            name="file_avabilitydesignorarchitecturedocumention",
            field=models.FileField(default=None, upload_to="induction2/"),
        ),
        migrations.AlterField(
            model_name="projectinduction",
            name="file_avabilitysafetohostcertificate",
            field=models.FileField(default=None, upload_to="induction1/"),
        ),
        migrations.AlterField(
            model_name="projectinduction",
            name="file_avabilityvarepotfromvender",
            field=models.FileField(default=None, upload_to="induction/"),
        ),
    ]
