# Generated by Django 4.2.2 on 2023-07-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_auditcomplition_file_finalauditreport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="auditexecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caseno", models.IntegerField(null=True)),
                ("victimip", models.CharField(max_length=80, null=True)),
                ("victimaddress", models.CharField(max_length=80, null=True)),
                ("maliciousip", models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
