# Generated by Django 4.2.2 on 2023-08-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_auditexecution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditexecution",
            name="maliciousip",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="auditexecution",
            name="victimaddress",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="auditexecution",
            name="victimip",
            field=models.IntegerField(null=True),
        ),
    ]
