# Generated by Django 4.2.2 on 2023-08-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_alter_auditexecution_maliciousip_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="auditreport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdfFile", models.FileField(default=None, upload_to="auditreport/")),
            ],
        ),
        migrations.CreateModel(
            name="vareport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdfFile", models.FileField(default=None, upload_to="vareport/")),
            ],
        ),
    ]
