# Generated by Django 4.2.2 on 2023-08-28 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_auditreport_vareport"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditreport",
            old_name="pdfFile",
            new_name="file_pdfFile",
        ),
        migrations.RenameField(
            model_name="vareport",
            old_name="pdfFile",
            new_name="file_pdfFile",
        ),
    ]
